version: "3.9"
services:
  readme.file-vault.mongodb:
    image: mongo:4.2
    container_name: readme.file-vault.mongodb

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - ${MONGO_PORT}:27017

    volumes:
      - readme.file-vault.mongodb:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/readme-file-vault --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  readme.file-vault.mongodb.ui:
    image: mongo-express:1.0.2-20
    restart: always
    container_name: readme.file-vault.mongodb.ui

    ports:
      - 8084:8081

    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@readme.file-vault.mongodb:27017/

volumes:
  readme.file-vault.mongodb:
